vci-issuers.json

hand-crafted, but validated json

UCHealth (UCSD, Irvine)

---

vci-issuers.json

@jdkizer9, UCSD is in both this PR and #6.

Contra Costa, Lehigh, Cedars-Sinai

---

vci-issuers.json

add second url for UCSD

---

vci-issuers.json

Entry validates at SECLEVEL 2.

Add entry for Community Medical Centers

---

vci-issuers.json

add UnityPoint

---

vci-issuers.json

@jdkizer9 We figured out that the problem was case-sensitivity. This is the updated version that works. Would it be possible to merge this fix quicker than our normal schedule since they've been live on the feature?
Thanks for any help!

fix Advocate Aurora Health

---

vci-issuers.json

This pull request adds Government of Yukon as an issuer.
A submission via the Google form was also made by my colleague @ygdaverogers.

Add Government of Yukon

---

vci-issuers.json

https://epicarr02.spectrumhealth.org/EpicFHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Spectrum Health

---

vci-issuers.json

https://epicproxy.uvmhealth.org/FHIR-ARR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add The University of Vermont Medical Center

---

vci-issuers.json

https://epicproxy.et1058.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Montage Health

---

vci-issuers.json

https://epicservicegw.froedtert.com/FHIRproxyPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Froedtert Health

---

vci-issuers.json

https://rxedi.bmhcc.org/prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Baptist Memorial Health Care

---

vci-issuers.json

https://iatrius.atriushealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Atrius Health

---

vci-issuers.json

https://uhealthsoap.med.miami.edu/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add UHealth – University of Miami Health System

---

vci-issuers.json

https://epicfhir.phs.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Presbyterian Healthcare Services

---

vci-issuers.json

https://epicproxy.et1057.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Molina Healthcare

---

vci-issuers.json

https://haiku.sparrow.org/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Sparrow Health System

---

vci-issuers.json

https://eprescribe-p.medisys.org/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add MediSys Health Network

---

vci-issuers.json

https://fhirprd.edward.org/fhirprd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add DuPage Medical Group and Edward-Elmhurst Health

---

vci-issuers.json

https://webservices.hawaiipacifichealth.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hawaii Pacific Health

---

vci-issuers.json

https://mhssp.mhs.net/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Memorial Healthcare System

---

vci-issuers.json

https://eparp.sbch.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Cottage Health

---

vci-issuers.json

https://fhir.ssmhc.com/Fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add SSM Health

---

vci-issuers.json

https://epincoming.slhs.org/Interconnect-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add St. Luke’s Health System (Idaho)

---

vci-issuers.json

https://fhir.lakelandregional.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Spectrum Health Lakeland

---

vci-issuers.json

https://eproxy.mercycare.org/oauth2/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Mercy Medical Center

---

vci-issuers.json

https://fhir.seattlechildrens.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Seattle Children’s

---

vci-issuers.json

https://fhir.guthrie.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add The Guthrie Clinic

---

vci-issuers.json

https://api.baptist-health.org/Interconnect-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Baptist Health

---

vci-issuers.json

https://moc.beaumont.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Beaumont Health

---

vci-issuers.json

https://interconnect.wellspan.org/interconnect-prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add WellSpan Health

---

vci-issuers.json

https://scproxy.gundersenhealth.org/FHIRARR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Gundersen Health System

---

vci-issuers.json

https://epicproxy.hosp.wisc.edu/FhirProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add UW Health

---

vci-issuers.json

https://epicmobile.centracare.com/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add CentraCare

---

vci-issuers.json

https://epic-rproxyprod.coh.org/Interconnect-FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add City of Hope

---

vci-issuers.json

https://epicprisfd01.wpahs.org/PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Allegheny Health Network

---

vci-issuers.json

https://epic-arr.utmb.edu/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Texas Medical Branch

---

vci-issuers.json

https://prd.salemhealth.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Salem Health

---

vci-issuers.json

https://rx.premierhealthpartners.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Premier Health

---

vci-issuers.json

https://sshic.southshorehealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add South Shore Health

---

vci-issuers.json

https://epicsoap.carle.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Carle Foundation Hospital

---

vci-issuers.json

https://apiservices.sutterhealth.org/ifs/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Sutter Health

---

vci-issuers.json

https://common.virginiahospitalcenter.com/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Virginia Hospital Center

---

vci-issuers.json

https://epicproxy.et0830.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Franciscan Missionaries of Our Lady Health System, Inc.

---

vci-issuers.json

https://epicproxy.et0996.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add UConn Health

---

vci-issuers.json

https://epicproxy.hhchealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hartford HealthCare

---

vci-issuers.json

https://epicproxy.mhsjvl.org/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Mercyhealth

---

vci-issuers.json

https://epicproxy.et1038.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add EPIC Management

---

vci-issuers.json

https://EpicIntprxyPRD.swmed.edu/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Texas Southwestern Medical Center

---

vci-issuers.json

https://fhir.renown.org/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Renown Health

---

vci-issuers.json

https://interconnect.lcmchealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add LCMC Health

---

vci-issuers.json

https://epicproxy.et1178.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add The University of Texas Health Science Center at Houston

---

scripts/common.py
scripts/test/common_test.py
scripts/test/fixtures/sample_directory.json
scripts/validate_entries.py
vci-issuers.json

Adds support for `website` and `canonicalIss` properties
Resolves #52

Add support for new metadata properties

---

vci-issuers.json

https://webproxyprd.monroeclinic.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Monroe Clinic

---

vci-issuers.json

https://fhir.mainehealth.org/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add MaineHealth

---

vci-issuers.json

https://erx.aspirus.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Aspirus

---

vci-issuers.json

https://epicproxy.et1024.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add South Georgia Medical Center

---

vci-issuers.json

https://ssproxy.pennhealth.com/PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Penn Medicine

---

vci-issuers.json

https://epicmobile.johnshopkins.edu/FHIR_PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Johns Hopkins Medicine

---

vci-issuers.json

https://epicsoap.stormontvail.org/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Stormont-Vail

---

vci-issuers.json

https://eportaltest.gbmc.org/fhir-tst/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Greater Baltimore Medical Center

---

vci-issuers.json

https://epicicfore.quadmedical.com/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add QuadMed

---

vci-issuers.json

https://epcapp.mhd.com/arr-prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Methodist Health System

---

vci-issuers.json

https://epicproxy.et1052.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Premise Health

---

vci-issuers.json

https://mepic.hackensackumc.net/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hackensack Meridian Health

---

vci-issuers.json

https://ema.franciscanalliance.org/FHIR_PROXY/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Franciscan Alliance

---

vci-issuers.json

https://mobileprod.arcmd.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Austin Regional Clinic

---

vci-issuers.json

https://fhir.chppoc.org/Fhir-External/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Pediatric Physicians' Organization at Children's

---

vci-issuers.json

https://arrprd.southeasthealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Southeast Health

---

vci-issuers.json

https://ssrx.ksnet.com/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Kelsey-Seybold Clinic

---

vci-issuers.json

https://epicprod-mobile.parkview.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Parkview Health

---

example-issuer.json

Added an example of a complex issuer and formatted the examples to show valid JSON.

Update examples to include new metadata

---

vci-issuers.json

https://epicproxy.et1095.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Kennedy Krieger Institute

---

vci-issuers.json

https://fhir.memorialcare.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add MemorialCare

---

vci-issuers.json

https://epicproxy.et0905.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Atrium Health

---

vci-issuers.json

https://epicproxy.et1055.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Mary Washington Healthcare

---

vci-issuers.json

https://m.essentiahealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Essentia Health

---

vci-issuers.json

https://soapproxy.umc.edu/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Mississippi Medical Center

---

vci-issuers.json

https://epicproxy.et1031.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Bryan Health

---

vci-issuers.json

https://epicproxy.et1127.epichosted.com/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add United Health Services

---

vci-issuers.json

https://fhir.genesishcs.org/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Genesis Healthcare System

---

vci-issuers.json

https://epicproxy.et0967.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Erlanger Health System

---

vci-issuers.json

@jdkizer9 - UMMS would greatly appreciate your review on this PR, today, if possible

add University of Maryland Medical System

---

vci-issuers.json

https://ehrmobile.monument.health/interconnect-prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Monument Health

---

vci-issuers.json

https://scripts.prevea.com/FHIR-ARR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hospital Sisters Health System

---

vci-issuers.json

https://epicedge.upstate.edu/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add SUNY Upstate

---

vci-issuers.json

https://lmcrcs.lexmed.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Lexington Medical Center

---

vci-issuers.json

https://webproxy.mynovant.org/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Novant Health

---

vci-issuers.json

https://epicrp.firsthealth.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add FirstHealth of the Carolinas

---

vci-issuers.json

https://epicmobile.ohsu.edu/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Oregon Health & Science University

---

vci-issuers.json

https://epicrpprd.inova.org/fhirrp/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Inova Health System

---

vci-issuers.json

https://ic.valleychildrens.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Valley Children’s Healthcare

---

vci-issuers.json

https://epicproxy.et1240.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add El Rio Health

---

vci-issuers.json

https://epicproxy.et1222.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add GW University Medical Faculty Associates

---

vci-issuers.json

https://fhir.archildrens.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Arkansas Children’s

---

vci-issuers.json

https://arrprd.metrohealth.net/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Michigan Health-West

---

vci-issuers.json

https://epicproxy.et0927.epichosted.com/VCI_PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hospital for Special Surgery

---

vci-issuers.json

https://eprescribe.sanfordhealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Sanford Health

---

vci-issuers.json

https://soap.wellmont.org/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Ballad Health

---

vci-issuers.json

https://epicproxy.et0764.epichosted.com/Fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Confluence Health

---

vci-issuers.json

https://epic-soap.wakemed.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add WakeMed

---

vci-issuers.json

https://epic-fhir-prd.upmc.com/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Pittsburgh Medical Center (UPMC)

---

vci-issuers.json

https://epicsoap.nortonhealthcare.org/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Norton Healthcare

---

vci-issuers.json

https://epicproxy.et1085.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add UI Health

---

vci-issuers.json

https://fhir.hurleymc.com/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hurley Medical Center

---

vci-issuers.json

https://epichaiku.chs-mi.com/FHIRPROXY/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Covenant Healthcare

---

vci-issuers.json

https://eweb.peninsula.org/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add TidalHealth

---

vci-issuers.json

https://wavesurescripts.sansumclinic.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Sansum Clinic

---

vci-issuers.json

https://prodsoap1.tgh.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Tampa General Hospital and University of South Florida

---

vci-issuers.json

https://meritus-rev-prd.meritushealth.com/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Meritus Health

---

vci-issuers.json

https://tpc-shield.tpcllp.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add The Portland Clinic

---

vci-issuers.json

https://fhir.slhn.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add St. Luke’s University Health Network

---

vci-issuers.json

https://LHSPDXFHIRPRD.LHS.ORG/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Legacy Health

---

vci-issuers.json

https://emrproxy.mcfarlandclinic.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Health Ventures

---

vci-issuers.json

https://epicproxy.et1130.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University Health

---

vci-issuers.json

https://mobileapps.texaschildrens.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC/

add Texas Children’s Hospital

---

vci-issuers.json

https://soapprod.tvc.org/ARR-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Vancouver Clinic

---

vci-issuers.json

replacing ISS since the current endpoint was a non-production endpoint submitted in error.

fix Henry Ford Health System

---

vci-issuers.json

https://geisapi.geisinger.edu/FHIR_PROD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Geisinger

---

vci-issuers.json

https://pmh-vmhaitst-01.pmh.org/FHIRPOC/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Parkland Health

---

vci-issuers.json

https://epicarr.emc.org/EMC_FHIR_PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Eisenhower Health

---

vci-issuers.json

https://scvhhsfhir.sccgov.org/interconnect-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add County of Santa Clara Health System

---

vci-issuers.json

https://edhwebportal.hitchcock.org/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Dartmouth-Hitchcock Health

---

vci-issuers.json

https://epicsoapproxyprd.mountsinai.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Mount Sinai Health System

---

vci-issuers.json

https://fhir.myeverettclinic.com/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Optum WA

---

vci-issuers.json

https://fhirprd.reliantmedicalgroup.org/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Reliant Medical Group

---

vci-issuers.json

https://webproxy.piedmont.org/ARR-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Piedmont Healthcare/Affiliates and Shepherd Center

---

vci-issuers.json

https://proxy.christushealth.org/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add CHRISTUS Health

---

vci-issuers.json

https://fhir.kansashealthsystem.com/interconnect-PRD_FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Kansas

---

vci-issuers.json

https://epicrpx.shannonhealth.org/FHIR_ARR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Shannon Health

---

vci-issuers.json

https://fhir.epic.medical.washington.edu/FHIR-Proxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add UW Medicine

---

vci-issuers.json

https://epicproxy.et0943.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Yakima Valley Farm Workers Clinic

---

vci-issuers.json

https://rpprod.riversidehealthcare.net/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Riverside Healthcare

---

vci-issuers.json

https://rproxy.novohtg.com/OAUTHPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add NOVO Health Technology Group

---

vci-issuers.json

https://sfd.fairview.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Fairview Health Services

---

vci-issuers.json

https://apps.mywvuchart.com/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add WVU Medicine

---

vci-issuers.json

https://interconnect.honorhealth.com/Interconnect-FHIR-PRD/api/epic/2021/security/open/eckeys/32001/SHC

add HonorHealth

---

vci-issuers.json

https://epicproxy.et1138.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Brown and Toland Physicians

---

vci-issuers.json

https://epicproxy.et1043.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add The Brooklyn Hospital Center

---

vci-issuers.json

https://eprescribing.accesscommunityhealth.net/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Access Community Health Network

---

vci-issuers.json

https://epicproxy.lghealth.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Lancaster General Health

---

vci-issuers.json

https://interconapps.uchospitals.edu/PRD-FHIR-Proxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Chicago Medical Center

---

vci-issuers.json

https://soap.crmcwy.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Cheyenne Regional Medical Center

---

vci-issuers.json

https://esoap.mihs.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Valleywise Health

---

vci-issuers.json

https://fhirprod.musc.edu/fhirprod/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Medical University of South Carolina

---

vci-issuers.json

https://epicproxy.rush.edu/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Rush University Medical Center

---

vci-issuers.json

https://soapproxy.atlantichealth.org/FHIRPrd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Atlantic Health System

---

vci-issuers.json

https://epicproxy.et1197.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hoag Clinic

---

vci-issuers.json

https://epicproxy.et1077.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Olmsted Medical Center

---

scripts/common.py
scripts/identify_entries_missing_cors.py

These are currently set up as `WARNING`, but will be converted to `ERROR` after a grace period of _n_ days.

Added CORS configuration checks

---

vci-issuers.json

complete overwrite since was erroneously a non-production endpoint

fix Greater Baltimore Medical Center

---

vci-issuers.json

https://epicproxy.institute.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add The Institute for Family Health

---

vci-issuers.json

https://epicproxypda.nychhc.org/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add New York City Health and Hospitals

---

vci-issuers.json

https://epicproxy.et1146.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Salinas Valley Memorial Healthcare System

---

vci-issuers.json

https://arr.mysrhs.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Singing River Health System

---

vci-issuers.json

https://epicproxy.connecticutchildrens.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Connecticut Children’s

---

vci-issuers.json

https://arr01.service.vumc.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Vanderbilt University Medical Center

---

vci-issuers.json

https://fhir.conemaugh.org/arr-fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Conemaugh

---

vci-issuers.json

https://ocsoapprd.nebraskamed.com/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Nebraska Medicine

---

vci-issuers.json

https://psacesoap.whhs.com/interconnect-fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Washington Hospital Healthcare System

---

vci-issuers.json

https://arrprod.midmichigan.net/ProdFHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add MidMichigan

---

vci-issuers.json

https://epicproxy.et1193.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Louisville Physicians

---

vci-issuers.json

https://epicproxy.et1153.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add New Jersey Urology

---

vci-issuers.json

website for Nebraska Medicine

---

vci-issuers.json

https://epicapp.mylrh.org/OAuth2/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Lakeland Regional Health

---

vci-issuers.json

https://epicproxy.et1007.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Main Line Health

---

vci-issuers.json

https://proxy.eskenazihealth.edu/FHIR-Proxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Eskenazi Health

---

vci-issuers.json

https://epicfhir.sentara.com/ARR-FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Sentara Healthcare

---

vci-issuers.json

https://epicsoap.altru.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Altru Health System

---

vci-issuers.json

https://haiku.northshore.org/Interconnect-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add NorthShore University HealthSystem

---

vci-issuers.json

https://epicpproxy.southcoast.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Southcoast Health

---

vci-issuers.json

https://epic.garnethealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Garnet Health

---

vci-issuers.json

Full fix not using Canonical ISS since original was in error.

fix Parkland Health

---

vci-issuers.json

https://epicproxy.et0946.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Palos Health

---

vci-issuers.json

https://fhir.clinical.bcm.edu/stage1fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Baylor Medicine

---

vci-issuers.json

https://epicsoap.bmctotalcare.com/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Summit Health

---

vci-issuers.json

https://sclprdproxy.sclhs.net/FHIRPRD-2017/api/epic/2021/Security/Open/EcKeys/32001/SHC

add SCL Health

---

vci-issuers.json

https://fhir.laheyhealth.org/proxy-prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Lahey Health

---

vci-issuers.json

https://epicmobile.nhrmc.org/OAuth2-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add New Hanover Regional Medical Center

---

vci-issuers.json

https://fhir.johnmuirhealth.com/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add John Muir Health

---

vci-issuers.json

https://epicproxy.et1149.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Cape Cod HealthCare

---

vci-issuers.json

https://ebmobile14.ebnhc.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add East Boston Neighborhood Health Center

---

vci-issuers.json

https://epicproxy.et0915.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC/

add Prisma Health

---

vci-issuers.json

https://FHIR.valleymed.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Valley Medical Center

---

vci-issuers.json

https://epicsoap.wellstar.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Wellstar

---

vci-issuers.json

https://eiclbext.nmhs.net/interconnect-fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC

add North Mississippi Health Services

---

vci-issuers.json

https://prodrx919.martinhealth.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Cleveland Clinic Martin Health

---

vci-issuers.json

https://soapprod.multicare.org/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add MultiCare

---

vci-issuers.json

https://sfd.stanfordmed.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC/

add Stanford Health Care

---

vci-issuers.json

https://webproxyprd.med.utah.edu/FHIRMyChart/api/epic/2021/Security/Open/EcKeys/32001/SHC

add University of Utah Health

---

vci-issuers.json

https://epicproxy.et0971.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add AnMed Health

---

vci-issuers.json

https://mobile.adventhealth.com/oauth2-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add AdventHealth

---

vci-issuers.json

https://epicproxy.et1013.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Hill Physicians Medical Group

---

vci-issuers.json

https://hkc.nationwidechildrens.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Nationwide Children’s Hospital

---

vci-issuers.json

https://epicproxy.et1220.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Reid Health

---

vci-issuers.json

https://webproxy.comhs.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Community Healthcare System

---

vci-issuers.json

now Rush University System for Health

rename Rush University Medical Center

---

vci-issuers.json

https://epicproxy.et1200.epichosted.com/oauth2-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add VCU Health

---

vci-issuers.json

https://prodinterconnect.leonmedicalcenters.com/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Leon Medical Centers

---

vci-issuers.json

https://epicproxy.et0578.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Cooper University Healthcare

---

vci-issuers.json

https://api.vaulthealth.com/smart

add Vault Health

---

vci-issuers.json

https://carepath.health-partners.org/Proxy-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC
https://haiku.bshsi.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Bon Secours Mercy Health and Bon Secours Health System

---

vci-issuers.json

add District of Columbia Department of Health

---

vci-issuers.json

https://epicproxy.et0815.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Children’s Wisconsin

---

vci-issuers.json

https://fhir.omhs.org/rp-prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Owensboro Health

---

vci-issuers.json

adding https://www.owensborohealth.org to Owensboro Health entry

website for Owensboro Health

---

vci-issuers-metadata.json

Change Alberta country field from US to Canada.
Remove trailing commas.

Fix metadata country for Alberta

---

vci-issuers.json

https://epicproxy.et1235.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Self Regional Healthcare

---

scripts/vci-directory-auditor/README.md
scripts/vci-directory-auditor/src/index.ts

Added option to skip the TLS configuration check in the directory audit script.

Added option to skip the TLS audit.

---

vci-issuers.json

https://yrmccare1.yumaregional.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Yuma Regional Medical Center

---

vci-issuers.json

https://surescripts.gmh.edu/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Grady Health

---

vci-issuers.json

https://epicproxyprd.solutionhealth.org/FHIR_PROD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add SolutionHealth

---

vci-issuers.json

Add new ISS: https://epicproxy.et0761.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC to make canonical in Piece 2

fix Tampa General Hospital and University of South Florida Piece 1

---

vci-issuers.json

https://mychart.methodisthospitals.org/FHIR-ARR/api/epic/2021/Security/Open/EcKeys/32001/SHC/.well-known/jwks.json

add Methodist Hospitals (IN)

---

vci-issuers.json

https://hscsesoap.hscs.virginia.edu/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC/.well-known/jwks.json

add UVA Health

---

vci-issuers.json

https://epicproxy.bhsi.com/PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Baptist Healthcare System

---

.github/workflows/test-scripts-pass.yaml
.github/workflows/validate-issuers-on-push-pass.yaml

Added push triggers to status checks to ensure required checks run on nightly audit push

Added push triggers to status checks

---

vci-issuers.json

https://epic-ext.trinity-health.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Trinity Health

---

vci-issuers.json

https://epicprdext.stfranciscare.org/FhirProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Trinity Health of New England

---

vci-issuers.json

https://epicproxy.et1296.epichosted.com/APIProxyPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Duly Health and Care

---

vci-issuers.json

https://www.testdirectly.com/KeyPublisher/0000500020/SHC

add Laborant LLC

---

vci-issuers.json

https://fhir.tmcaz.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Tucson Medical Center

---

vci-issuers.json

https://epx1.chsli.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Catholic Health

---

vci-issuers.json

https://www.hy-vee.com/my-pharmacy/static

add Hy-Vee

---

.github/workflows/deploy.yaml

This work is to include logs directory when we are uploading to S3.

including logs directory to sync with S3

---

vci-issuers.json

https://epicproxy.et1131.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Orlando Health and Bayfront Health St. Petersburg

---

vci-issuers-metadata.json

Updated locations, Round 8

---

vci-issuers.json

https://epicproxy.et0939.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Spartanburg Regional Healthcare System

---

.github/workflows/upload-snapshot.yaml

This adds any change to the main to push to S3. 
Includes file is vci-issuer.json and metadata.json

[PSDS] 1 - add action to upload vci-issuer and metadata to S3  

---

vci-issuers.json

https://external.fastmed.com/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add FastMed

---

vci-issuers.json

https://lsepprdsoap.lifespan.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Lifespan

---

vci-issuers.json

https://smarthealthcard.iisregistry.net/arkansas/issuer

add Arkansas Department of Health

---

vci-issuers-metadata.json
vci-issuers.json

https://fhir.mvhealthsystem.org/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Mohawk Valley Health System

---

vci-issuers-metadata.json
vci-issuers.json

Docket will soon be supporting Wyoming. They have asked to be included in the VCI project.

Add Wyoming

---

vci-issuers-metadata.json
vci-issuers.json

https://boomer.cchmc.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC

add Cincinnati Children's Hospital Medical Center

---

vci-issuers-metadata.json
vci-issuers.json

https://epicproxy.et1233.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add NCH Healthcare System

---

vci-issuers-metadata.json
vci-issuers.json

https://proxy.healthpartners.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

add HealthPartners

---

vci-issuers-metadata.json
vci-issuers.json

https://epicproxy.et1075.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

Add Alameda Health System

---

vci-issuers-metadata.json
vci-issuers.json

https://epicproxy.et1256.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

Add Health Choice Network

---

vci-issuers.json

Adding Methodist Le Bonheur to the VCI directory.

Update vci-issuers.json - adding Methodist Le Bonheur

---

vci-issuers-metadata.json

Update vci-issuers-metadata.json - adding Methodist Le Bonheur

---

scripts/requirements.txt

Attempts to get github actions automated tests to pass.

Add dependabot changes from last 18 months
